import { insertListItems } from './listService';
import {
  createRecipe,
  setRecipeIngredients,
  toggleRecipeFavorite,
} from './recipeService';
import { createMeal, setMealIngredients } from './mealService';
import { createStore } from './storeService';
import { clearAllLocalData } from './localDataService';
import { isSyncEnabled } from './supabaseClient';
import { getCurrentHouseholdId } from './householdService';
import { deleteHouseholdSyncedContent } from './deleteUserAppDataService';
import { normalize } from '../utils/normalize';
import { toDateString } from '../utils/dateUtils';
import type { ZoneKey, AisleEntry, RecipeCategory } from '../types/models';
import type { ListItemInsert } from './listService';
import { ZONE_KEYS } from '../data/zone';
import { zoneOrderToAisleOrder } from '../utils/storeUtils';

/**
 * Demo list — healthy American family staples. Field completeness varies on purpose
 * (sparse rows vs. fully filled) for App Store screenshots.
 * `linked_meal_refs` resolve after meals are created; names must match DEMO_MEALS.
 */
const DEMO_LIST_ITEMS: (Omit<ListItemInsert, 'user_id' | 'normalized_name' | 'linked_meal_ids'> & {
  linked_meal_refs?: string[];
})[] = [
  // Bare minimum: name + category + zone only
  {
    name: 'Cucumber',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: false,
    linked_meal_refs: [],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Bananas',
    category: 'Fruit',
    zone_key: 'produce' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: true,
    linked_meal_refs: ['Berry banana smoothie'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
  // Quantity only (no notes, brand, or meal links)
  {
    name: 'Baby carrots',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'lb',
    notes: null,
    is_checked: false,
    linked_meal_refs: [],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Avocados',
    category: 'Produce',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 4,
    quantity_unit: 'ea',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Taco night'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  // Notes + checked, sparse elsewhere
  {
    name: 'Broccoli crowns',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: 'Steam or roast — kids like with cheese',
    is_checked: false,
    linked_meal_refs: ['Tofu stir-fry'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Honeycrisp apples',
    category: 'Fruit',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 6,
    quantity_unit: 'ea',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Apple & peanut butter snack'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Fresh cilantro',
    category: 'Herbs',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'bunch',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Taco night', 'Turkey and bean chili'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Yellow onion',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 2,
    quantity_unit: 'ea',
    notes: null,
    is_checked: true,
    linked_meal_refs: ['Chicken & brown rice soup', 'Taco night', 'Turkey and bean chili'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Garlic',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'head',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Sheet-pan lemon salmon', 'Tofu stir-fry'],
    brand_preference: null,
    substitute_allowed: false,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Lemons',
    category: 'Fruit',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 3,
    quantity_unit: 'ea',
    notes: 'For salmon + water',
    is_checked: false,
    linked_meal_refs: ['Sheet-pan lemon salmon'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Cherry tomatoes',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'pt',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Turkey roll-ups', 'Quinoa veggie bowl'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Baby spinach',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 10,
    quantity_unit: 'oz',
    notes: 'Salads & eggs',
    is_checked: false,
    linked_meal_refs: ['Veggie scramble & toast', 'Berry banana smoothie', 'Side salad'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'high',
    is_recurring: true,
  },
  {
    name: 'Bell peppers',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 3,
    quantity_unit: 'ea',
    notes: 'Mix of colors',
    is_checked: false,
    linked_meal_refs: ['Tofu stir-fry', 'Taco night'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Sweet potatoes',
    category: 'Vegetables',
    zone_key: 'produce' as ZoneKey,
    quantity_value: 4,
    quantity_unit: 'ea',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Sheet-pan lemon salmon'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Wild-caught salmon fillets',
    category: 'Seafood',
    zone_key: 'meat_seafood' as ZoneKey,
    quantity_value: 1.5,
    quantity_unit: 'lb',
    notes: 'Skin on for sheet pan',
    is_checked: false,
    linked_meal_refs: ['Sheet-pan lemon salmon'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'high',
    is_recurring: false,
  },
  {
    name: 'Ground turkey 93% lean',
    category: 'Poultry',
    zone_key: 'meat_seafood' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'lb',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Taco night', 'Turkey and bean chili'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Boneless chicken thighs',
    category: 'Poultry',
    zone_key: 'meat_seafood' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Chicken & brown rice soup'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Firm tofu',
    category: 'Protein',
    zone_key: 'meat_seafood' as ZoneKey,
    quantity_value: 14,
    quantity_unit: 'oz',
    notes: 'Press 20 min',
    is_checked: false,
    linked_meal_refs: ['Tofu stir-fry'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: '2% milk',
    category: 'Dairy',
    zone_key: 'dairy_eggs' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'gal',
    notes: null,
    is_checked: true,
    linked_meal_refs: ['Oatmeal with berries', 'Weekend pancakes'],
    brand_preference: 'Organic Valley',
    substitute_allowed: true,
    priority: 'high',
    is_recurring: true,
  },
  {
    name: 'Plain Greek yogurt',
    category: 'Dairy',
    zone_key: 'dairy_eggs' as ZoneKey,
    quantity_value: 32,
    quantity_unit: 'oz',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Greek yogurt power bowl', 'Turkey roll-ups', 'Berry banana smoothie'],
    brand_preference: 'Chobani',
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Eggs',
    category: 'Dairy',
    zone_key: 'dairy_eggs' as ZoneKey,
    quantity_value: 18,
    quantity_unit: 'count',
    notes: 'Cage-free if on sale',
    is_checked: false,
    linked_meal_refs: ['Veggie scramble & toast', 'Weekend pancakes'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Low-fat cottage cheese',
    category: 'Dairy',
    zone_key: 'dairy_eggs' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Greek yogurt power bowl'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'String cheese',
    category: 'Dairy',
    zone_key: 'dairy_eggs' as ZoneKey,
    quantity_value: 12,
    quantity_unit: 'count',
    notes: 'School lunches',
    is_checked: false,
    linked_meal_refs: [],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
  {
    name: 'Whole wheat tortillas',
    category: 'Bakery',
    zone_key: 'bakery_deli' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'pack',
    notes: '8-inch',
    is_checked: false,
    linked_meal_refs: ['Taco night'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Whole grain bread',
    category: 'Bread',
    zone_key: 'bakery_deli' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'loaf',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Veggie scramble & toast', 'Turkey roll-ups', 'Apple & peanut butter snack'],
    brand_preference: "Dave's Killer Bread",
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Frozen mixed berries',
    category: 'Fruit',
    zone_key: 'frozen' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Oatmeal with berries', 'Berry banana smoothie'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
  {
    name: 'Frozen edamame',
    category: 'Vegetables',
    zone_key: 'frozen' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'bag',
    notes: 'Shelled — quick protein snack',
    is_checked: false,
    linked_meal_refs: [],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Old-fashioned rolled oats',
    category: 'Grains',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'canister',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Oatmeal with berries'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'White whole wheat flour',
    category: 'Baking',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 5,
    quantity_unit: 'lb',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Weekend pancakes'],
    brand_preference: 'King Arthur',
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Quinoa',
    category: 'Grains',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 2,
    quantity_unit: 'lb',
    notes: 'Rinse before cooking',
    is_checked: false,
    linked_meal_refs: ['Quinoa veggie bowl'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Brown rice',
    category: 'Grains',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 2,
    quantity_unit: 'lb',
    notes: null,
    is_checked: true,
    linked_meal_refs: ['Chicken & brown rice soup', 'Tofu stir-fry'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
  {
    name: 'Whole wheat pasta',
    category: 'Pasta',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'lb',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Whole wheat pasta night'],
    brand_preference: 'Barilla',
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Jarred marinara',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'jar',
    notes: 'Low sugar',
    is_checked: false,
    linked_meal_refs: ['Whole wheat pasta night'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Low-sodium chicken broth',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 2,
    quantity_unit: 'carton',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Chicken & brown rice soup'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'high',
    is_recurring: false,
  },
  {
    name: 'Canned black beans',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 2,
    quantity_unit: 'can',
    notes: 'Rinse well',
    is_checked: false,
    linked_meal_refs: ['Taco night', 'Turkey and bean chili', 'Quinoa veggie bowl'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: false,
  },
  {
    name: 'Natural peanut butter',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'jar',
    notes: 'Ingredients: peanuts + salt only',
    is_checked: false,
    linked_meal_refs: ['Apple & peanut butter snack'],
    brand_preference: null,
    substitute_allowed: false,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Raw almonds',
    category: 'Snacks',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Greek yogurt power bowl'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
  {
    name: 'Extra virgin olive oil',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'bottle',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Sheet-pan lemon salmon', 'Tofu stir-fry', 'Side salad'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'normal',
    is_recurring: true,
  },
  {
    name: 'Low-sodium soy sauce',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'bottle',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Tofu stir-fry'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Hummus',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'tub',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Turkey roll-ups'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Taco seasoning',
    category: 'Pantry',
    zone_key: 'pantry' as ZoneKey,
    quantity_value: 1,
    quantity_unit: 'packet',
    notes: null,
    is_checked: false,
    linked_meal_refs: ['Taco night'],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: false,
  },
  {
    name: 'Sparkling water',
    category: 'Drinks',
    zone_key: 'snacks_drinks' as ZoneKey,
    quantity_value: 12,
    quantity_unit: 'can',
    notes: null,
    is_checked: false,
    linked_meal_refs: [],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
  {
    name: 'Paper towels',
    category: 'Household',
    zone_key: 'household_cleaning' as ZoneKey,
    quantity_value: null,
    quantity_unit: null,
    notes: null,
    is_checked: false,
    linked_meal_refs: [],
    brand_preference: null,
    substitute_allowed: true,
    priority: 'low',
    is_recurring: true,
  },
];

/**
 * Recipes — same theme; metadata density varies (some URL/notes/favorites empty).
 */
const DEMO_RECIPES: {
  name: string;
  servings: number;
  category?: RecipeCategory | null;
  recipe_url?: string | null;
  notes?: string | null;
  is_favorite?: boolean;
  ingredients: { name: string; quantity_value: number | null; quantity_unit: string | null; notes?: string | null }[];
}[] = [
  {
    name: 'Sheet-pan lemon salmon',
    servings: 4,
    category: 'dinner',
    recipe_url: 'https://www.eatingwell.com/recipe/276234/sheet-pan-honey-mustard-salmon-with-green-beans/',
    notes: 'Swap green beans for sweet potato cubes. 425°F until salmon flakes.',
    is_favorite: true,
    ingredients: [
      { name: 'Salmon fillets', quantity_value: 1.5, quantity_unit: 'lb', notes: 'skin on' },
      { name: 'Lemon', quantity_value: 1, quantity_unit: 'ea', notes: 'zest + juice' },
      { name: 'Garlic', quantity_value: 3, quantity_unit: 'clove', notes: 'minced' },
      { name: 'Olive oil', quantity_value: 2, quantity_unit: 'tbsp', notes: null },
      { name: 'Sweet potato', quantity_value: 2, quantity_unit: 'ea', notes: 'cubed' },
      { name: 'Salt and pepper', quantity_value: null, quantity_unit: null, notes: 'to taste' },
    ],
  },
  {
    name: 'Skillet turkey tacos',
    servings: 6,
    category: 'dinner',
    recipe_url: 'https://www.skinnytaste.com/turkey-taco-skillet/',
    notes: null,
    is_favorite: true,
    ingredients: [
      { name: 'Ground turkey', quantity_value: 1.25, quantity_unit: 'lb', notes: null },
      { name: 'Yellow onion', quantity_value: 0.5, quantity_unit: 'ea', notes: 'diced' },
      { name: 'Bell pepper', quantity_value: 1, quantity_unit: 'ea', notes: 'diced' },
      { name: 'Black beans', quantity_value: 1, quantity_unit: 'can', notes: 'drained' },
      { name: 'Taco seasoning', quantity_value: null, quantity_unit: null, notes: '1 packet or homemade' },
      { name: 'Whole wheat tortillas', quantity_value: 8, quantity_unit: 'ea', notes: 'warmed' },
      { name: 'Avocado', quantity_value: 2, quantity_unit: 'ea', notes: 'sliced' },
      { name: 'Cilantro', quantity_value: null, quantity_unit: null, notes: 'optional' },
    ],
  },
  {
    name: 'Chicken & brown rice soup',
    servings: 8,
    category: 'dinner',
    recipe_url: null,
    notes: 'Simmer until rice is tender. Freezes well.',
    is_favorite: false,
    ingredients: [
      { name: 'Chicken thighs', quantity_value: 1.5, quantity_unit: 'lb', notes: null },
      { name: 'Carrots', quantity_value: 3, quantity_unit: 'ea', notes: 'sliced' },
      { name: 'Celery', quantity_value: 3, quantity_unit: 'stalk', notes: null },
      { name: 'Onion', quantity_value: 1, quantity_unit: 'ea', notes: 'diced' },
      { name: 'Garlic', quantity_value: 4, quantity_unit: 'clove', notes: null },
      { name: 'Brown rice', quantity_value: 1, quantity_unit: 'cup', notes: 'uncooked' },
      { name: 'Chicken broth', quantity_value: 8, quantity_unit: 'cup', notes: 'low sodium' },
    ],
  },
  {
    name: 'Tofu vegetable stir-fry',
    servings: 4,
    category: 'dinner',
    recipe_url: null,
    notes: null,
    is_favorite: false,
    ingredients: [
      { name: 'Firm tofu', quantity_value: 14, quantity_unit: 'oz', notes: 'cubed' },
      { name: 'Bell peppers', quantity_value: 2, quantity_unit: 'ea', notes: null },
      { name: 'Broccoli', quantity_value: 2, quantity_unit: 'cup', notes: 'florets' },
      { name: 'Garlic', quantity_value: 2, quantity_unit: 'clove', notes: null },
      { name: 'Soy sauce', quantity_value: 3, quantity_unit: 'tbsp', notes: null },
      { name: 'Brown rice', quantity_value: 2, quantity_unit: 'cup', notes: 'cooked, for serving' },
    ],
  },
  {
    name: 'Whole wheat pancakes',
    servings: 4,
    category: 'breakfast',
    recipe_url: 'https://www.kingarthurbaking.com/recipes/whole-grain-pancakes-recipe',
    notes: 'Rest batter 5 minutes for fluffier cakes.',
    is_favorite: true,
    ingredients: [
      { name: 'White whole wheat flour', quantity_value: 1.5, quantity_unit: 'cup', notes: null },
      { name: 'Baking powder', quantity_value: 1, quantity_unit: 'tbsp', notes: null },
      { name: 'Eggs', quantity_value: 2, quantity_unit: 'count', notes: null },
      { name: 'Milk', quantity_value: 1.5, quantity_unit: 'cup', notes: null },
      { name: 'Maple syrup', quantity_value: null, quantity_unit: null, notes: 'for serving' },
    ],
  },
  {
    name: 'Turkey and bean chili',
    servings: 8,
    category: 'dinner',
    recipe_url: 'https://www.simplyrecipes.com/recipes/turkey_chili/',
    notes: null,
    is_favorite: false,
    ingredients: [
      { name: 'Ground turkey', quantity_value: 2, quantity_unit: 'lb', notes: null },
      { name: 'Onion', quantity_value: 1, quantity_unit: 'ea', notes: null },
      { name: 'Garlic', quantity_value: 4, quantity_unit: 'clove', notes: null },
      { name: 'Bell pepper', quantity_value: 1, quantity_unit: 'ea', notes: null },
      { name: 'Black beans', quantity_value: 2, quantity_unit: 'can', notes: null },
      { name: 'Diced tomatoes', quantity_value: 1, quantity_unit: 'can', notes: '28 oz' },
    ],
  },
  {
    name: 'Greek yogurt breakfast bowl',
    servings: 2,
    category: 'breakfast',
    recipe_url: null,
    notes: null,
    is_favorite: false,
    ingredients: [
      { name: 'Greek yogurt', quantity_value: 2, quantity_unit: 'cup', notes: null },
      { name: 'Berries', quantity_value: null, quantity_unit: null, notes: 'handful each' },
      { name: 'Almonds', quantity_value: 2, quantity_unit: 'tbsp', notes: 'chopped' },
    ],
  },
  {
    name: 'Berry banana smoothie',
    servings: 2,
    category: 'snack',
    recipe_url: null,
    notes: 'Add ice if too thick.',
    is_favorite: false,
    ingredients: [
      { name: 'Frozen mixed berries', quantity_value: 1, quantity_unit: 'cup', notes: null },
      { name: 'Banana', quantity_value: 1, quantity_unit: 'ea', notes: null },
      { name: 'Greek yogurt', quantity_value: 0.5, quantity_unit: 'cup', notes: null },
      { name: 'Spinach', quantity_value: 1, quantity_unit: 'cup', notes: 'optional' },
    ],
  },
];

/** Meals — planner spread; optional fields intentionally uneven for screenshots. */
const DEMO_MEALS: {
  name: string;
  slot: 'breakfast' | 'lunch' | 'dinner' | 'dessert' | 'custom';
  custom_slot_name?: string | null;
  dateOffset: number;
  recipe_ref?: string | null;
  recipe_url?: string | null;
  notes?: string | null;
  ingredients: {
    name: string;
    quantity_value: number | null;
    quantity_unit: string | null;
    notes?: string | null;
    brand_preference?: string | null;
  }[];
}[] = [
  {
    name: 'Veggie scramble & toast',
    slot: 'breakfast',
    dateOffset: 0,
    recipe_url: null,
    notes: null,
    ingredients: [
      { name: 'Eggs', quantity_value: 6, quantity_unit: 'count', notes: null },
      { name: 'Baby spinach', quantity_value: 2, quantity_unit: 'cup', notes: null },
    ],
  },
  {
    name: 'Greek yogurt power bowl',
    slot: 'breakfast',
    dateOffset: 0,
    recipe_ref: 'Greek yogurt breakfast bowl',
    recipe_url: null,
    notes: 'Top with whatever fruit is ripe',
    ingredients: [
      { name: 'Plain Greek yogurt', quantity_value: 2, quantity_unit: 'cup', notes: null },
      { name: 'Frozen mixed berries', quantity_value: 0.5, quantity_unit: 'cup', notes: 'thawed' },
      { name: 'Raw almonds', quantity_value: 3, quantity_unit: 'tbsp', notes: 'sliced', brand_preference: null },
      { name: 'Low-fat cottage cheese', quantity_value: 0.25, quantity_unit: 'cup', notes: 'optional', brand_preference: 'Good Culture' },
    ],
  },
  {
    name: 'Turkey roll-ups',
    slot: 'lunch',
    dateOffset: 0,
    recipe_url: null,
    notes: 'Sliced deli turkey from the counter if you prefer',
    ingredients: [
      { name: 'Whole grain bread', quantity_value: 4, quantity_unit: 'slice', notes: 'crusts optional' },
      { name: 'Hummus', quantity_value: 4, quantity_unit: 'tbsp', notes: null },
      { name: 'Cherry tomatoes', quantity_value: 0.5, quantity_unit: 'cup', notes: 'halved' },
      { name: 'Cucumber', quantity_value: 0.25, quantity_unit: 'ea', notes: 'ribbons' },
    ],
  },
  {
    name: 'Sheet-pan lemon salmon',
    slot: 'dinner',
    dateOffset: 0,
    recipe_ref: 'Sheet-pan lemon salmon',
    recipe_url: 'https://www.eatingwell.com/recipe/276234/sheet-pan-honey-mustard-salmon-with-green-beans/',
    notes: 'Kids eat the sweet potato first',
    ingredients: [
      { name: 'Wild-caught salmon fillets', quantity_value: 1.25, quantity_unit: 'lb', notes: null },
      { name: 'Sweet potatoes', quantity_value: 3, quantity_unit: 'ea', notes: 'cubed' },
      { name: 'Lemons', quantity_value: 1, quantity_unit: 'ea', notes: 'juice over fish' },
      { name: 'Extra virgin olive oil', quantity_value: 2, quantity_unit: 'tbsp', notes: null },
      { name: 'Garlic', quantity_value: 3, quantity_unit: 'clove', notes: 'minced' },
    ],
  },
  {
    name: 'Taco night',
    slot: 'dinner',
    dateOffset: 1,
    recipe_ref: 'Skillet turkey tacos',
    recipe_url: 'https://www.skinnytaste.com/turkey-taco-skillet/',
    notes: null,
    ingredients: [
      { name: 'Ground turkey 93% lean', quantity_value: 1, quantity_unit: 'lb', notes: null },
      { name: 'Yellow onion', quantity_value: 0.5, quantity_unit: 'ea', notes: null },
      { name: 'Bell peppers', quantity_value: 2, quantity_unit: 'ea', notes: null },
      { name: 'Canned black beans', quantity_value: 1, quantity_unit: 'can', notes: 'rinsed' },
      { name: 'Whole wheat tortillas', quantity_value: 8, quantity_unit: 'ea', notes: null },
      { name: 'Avocados', quantity_value: 2, quantity_unit: 'ea', notes: null },
      { name: 'Fresh cilantro', quantity_value: 1, quantity_unit: 'bunch', notes: null },
    ],
  },
  {
    name: 'Quinoa veggie bowl',
    slot: 'lunch',
    dateOffset: 1,
    recipe_url: null,
    notes: null,
    ingredients: [
      { name: 'Quinoa', quantity_value: 1, quantity_unit: 'cup', notes: 'dry' },
      { name: 'Canned black beans', quantity_value: 1, quantity_unit: 'can', notes: null },
      { name: 'Cherry tomatoes', quantity_value: 1, quantity_unit: 'cup', notes: null },
    ],
  },
  {
    name: 'Apple & peanut butter snack',
    slot: 'custom',
    custom_slot_name: 'After school',
    dateOffset: 1,
    recipe_url: null,
    notes: null,
    ingredients: [
      { name: 'Honeycrisp apples', quantity_value: 2, quantity_unit: 'ea', notes: 'sliced' },
      { name: 'Natural peanut butter', quantity_value: 3, quantity_unit: 'tbsp', notes: null },
      { name: 'Whole grain bread', quantity_value: null, quantity_unit: null, notes: 'optional, for open-face' },
    ],
  },
  {
    name: 'Chicken & brown rice soup',
    slot: 'dinner',
    dateOffset: 2,
    recipe_ref: 'Chicken & brown rice soup',
    recipe_url: null,
    notes: 'Slow cooker on low 6–7 hours works great',
    ingredients: [
      { name: 'Boneless chicken thighs', quantity_value: 1.5, quantity_unit: 'lb', notes: null },
      { name: 'Brown rice', quantity_value: 0.75, quantity_unit: 'cup', notes: 'uncooked' },
      { name: 'Low-sodium chicken broth', quantity_value: 2, quantity_unit: 'carton', notes: null },
      { name: 'Yellow onion', quantity_value: 0.5, quantity_unit: 'ea', notes: null },
      { name: 'Garlic', quantity_value: 3, quantity_unit: 'clove', notes: null },
    ],
  },
  {
    name: 'Tofu stir-fry',
    slot: 'dinner',
    dateOffset: 2,
    recipe_ref: 'Tofu vegetable stir-fry',
    recipe_url: null,
    notes: null,
    ingredients: [
      { name: 'Firm tofu', quantity_value: 14, quantity_unit: 'oz', notes: null },
      { name: 'Bell peppers', quantity_value: 2, quantity_unit: 'ea', notes: null },
      { name: 'Broccoli crowns', quantity_value: 1, quantity_unit: 'head', notes: 'chopped' },
      { name: 'Low-sodium soy sauce', quantity_value: 3, quantity_unit: 'tbsp', notes: null },
      { name: 'Brown rice', quantity_value: 2, quantity_unit: 'cup', notes: 'cooked' },
    ],
  },
  {
    name: 'Oatmeal with berries',
    slot: 'breakfast',
    dateOffset: 3,
    recipe_url: null,
    notes: 'Cinnamon if the kids want it',
    ingredients: [
      { name: 'Old-fashioned rolled oats', quantity_value: 1, quantity_unit: 'cup', notes: 'dry, for family' },
      { name: '2% milk', quantity_value: 2, quantity_unit: 'cup', notes: null },
      { name: 'Frozen mixed berries', quantity_value: 1, quantity_unit: 'cup', notes: null },
    ],
  },
  {
    name: 'Whole wheat pasta night',
    slot: 'dinner',
    dateOffset: 3,
    recipe_url: null,
    notes: null,
    ingredients: [
      { name: 'Whole wheat pasta', quantity_value: 1, quantity_unit: 'lb', notes: null },
      { name: 'Jarred marinara', quantity_value: 1, quantity_unit: 'jar', notes: null },
    ],
  },
  {
    name: 'Berry banana smoothie',
    slot: 'breakfast',
    dateOffset: 4,
    recipe_ref: 'Berry banana smoothie',
    recipe_url: null,
    notes: null,
    ingredients: [
      { name: 'Frozen mixed berries', quantity_value: 1.5, quantity_unit: 'cup', notes: null },
      { name: 'Bananas', quantity_value: 1, quantity_unit: 'ea', notes: 'ripe' },
      { name: 'Plain Greek yogurt', quantity_value: 0.75, quantity_unit: 'cup', notes: null },
      { name: 'Baby spinach', quantity_value: 1, quantity_unit: 'handful', notes: 'they won’t taste it', brand_preference: null },
    ],
  },
  {
    name: 'Weekend pancakes',
    slot: 'breakfast',
    dateOffset: 4,
    recipe_ref: 'Whole wheat pancakes',
    recipe_url: 'https://www.kingarthurbaking.com/recipes/whole-grain-pancakes-recipe',
    notes: 'Double batch — freeze extras',
    ingredients: [
      { name: 'White whole wheat flour', quantity_value: 3, quantity_unit: 'cup', notes: null },
      { name: 'Eggs', quantity_value: 4, quantity_unit: 'count', notes: null },
      { name: '2% milk', quantity_value: 3, quantity_unit: 'cup', notes: null },
      { name: 'Baking powder', quantity_value: 2, quantity_unit: 'tbsp', notes: null },
    ],
  },
  {
    name: 'Side salad',
    slot: 'lunch',
    dateOffset: 4,
    recipe_url: null,
    notes: 'Simple vinaigrette: oil + lemon',
    ingredients: [
      { name: 'Baby spinach', quantity_value: 5, quantity_unit: 'oz', notes: null },
      { name: 'Extra virgin olive oil', quantity_value: 2, quantity_unit: 'tbsp', notes: null },
    ],
  },
  {
    name: 'Turkey and bean chili',
    slot: 'dinner',
    dateOffset: 5,
    recipe_ref: 'Turkey and bean chili',
    recipe_url: 'https://www.simplyrecipes.com/recipes/turkey_chili/',
    notes: null,
    ingredients: [
      { name: 'Ground turkey 93% lean', quantity_value: 2, quantity_unit: 'lb', notes: null },
      { name: 'Yellow onion', quantity_value: 1, quantity_unit: 'ea', notes: null },
      { name: 'Canned black beans', quantity_value: 2, quantity_unit: 'can', notes: null },
      { name: 'Bell peppers', quantity_value: 1, quantity_unit: 'ea', notes: null },
      { name: 'Garlic', quantity_value: 4, quantity_unit: 'clove', notes: null },
    ],
  },
  {
    name: 'Leftover night',
    slot: 'dinner',
    dateOffset: 6,
    recipe_url: null,
    notes: 'Clear the fridge before Sunday shop',
    ingredients: [{ name: 'Anything goes', quantity_value: null, quantity_unit: null, notes: null }],
  },
];

/** Store definitions: different types, section layouts, notes */
const DEMO_STORES: {
  name: string;
  store_type: 'generic' | 'kroger_style' | 'albertsons_style' | 'wholefoods_style' | 'costco_style' | 'traderjoes_style';
  aisle_order: AisleEntry[];
  notes?: string | null;
}[] = [
  {
    name: 'Downtown Grocery',
    store_type: 'generic',
    aisle_order: zoneOrderToAisleOrder([...ZONE_KEYS]),
    notes: 'Main weekly shop. Produce is at the entrance.',
  },
  {
    name: 'Kroger',
    store_type: 'kroger_style',
    aisle_order: [
      { type: 'builtin', key: 'produce' },
      { type: 'builtin', key: 'bakery_deli' },
      { type: 'custom', id: 'custom-dairy', name: 'Dairy & Eggs' },
      { type: 'custom', id: 'custom-meat', name: 'Meat & Seafood' },
      { type: 'builtin', key: 'frozen' },
      { type: 'builtin', key: 'pantry' },
      { type: 'builtin', key: 'snacks_drinks' },
      { type: 'custom', id: 'custom-pharmacy', name: 'Pharmacy' },
      { type: 'builtin', key: 'household_cleaning' },
      { type: 'builtin', key: 'personal_care' },
      { type: 'builtin', key: 'other' },
    ],
    notes: 'Pharmacy near back. ClickList pickup available.',
  },
  {
    name: 'Whole Foods',
    store_type: 'wholefoods_style',
    aisle_order: [
      { type: 'builtin', key: 'produce' },
      { type: 'builtin', key: 'bakery_deli' },
      { type: 'custom', id: 'custom-prepared', name: 'Prepared Foods' },
      { type: 'builtin', key: 'meat_seafood' },
      { type: 'builtin', key: 'dairy_eggs' },
      { type: 'builtin', key: 'frozen' },
      { type: 'builtin', key: 'pantry' },
      { type: 'builtin', key: 'snacks_drinks' },
      { type: 'builtin', key: 'household_cleaning' },
      { type: 'builtin', key: 'personal_care' },
      { type: 'builtin', key: 'other' },
    ],
    notes: 'Hot bar and salad bar near entrance. Bulk section in middle.',
  },
  {
    name: 'Costco',
    store_type: 'costco_style',
    aisle_order: [
      { type: 'custom', id: 'custom-produce', name: 'Produce' },
      { type: 'custom', id: 'custom-dairy', name: 'Dairy & Refrigerated' },
      { type: 'custom', id: 'custom-meat', name: 'Meat & Seafood' },
      { type: 'custom', id: 'custom-bakery', name: 'Bakery' },
      { type: 'custom', id: 'custom-frozen', name: 'Frozen' },
      { type: 'custom', id: 'custom-grocery', name: 'Grocery sections' },
      { type: 'custom', id: 'custom-household', name: 'Household' },
      { type: 'custom', id: 'custom-other', name: 'Other' },
    ],
    notes: 'Warehouse layout. Stock up on staples. Check rotisserie chicken.',
  },
  {
    name: "Trader Joe's",
    store_type: 'traderjoes_style',
    aisle_order: [
      { type: 'builtin', key: 'produce' },
      { type: 'builtin', key: 'dairy_eggs' },
      { type: 'builtin', key: 'meat_seafood' },
      { type: 'builtin', key: 'bakery_deli' },
      { type: 'builtin', key: 'frozen' },
      { type: 'builtin', key: 'pantry' },
      { type: 'builtin', key: 'snacks_drinks' },
      { type: 'builtin', key: 'household_cleaning' },
      { type: 'builtin', key: 'other' },
    ],
    notes: 'Smaller store, different layout. Great frozen section.',
  },
];

/** Clears all user data (local or Supabase) so demo loads into a clean slate. */
async function clearAllUserData(_userId: string): Promise<void> {
  if (!isSyncEnabled()) {
    await clearAllLocalData();
    return;
  }
  const householdId = await getCurrentHouseholdId();
  await deleteHouseholdSyncedContent(householdId);
}

export async function loadDemoData(userId: string): Promise<void> {
  // 0. Clear existing data so demo loads into a clean slate
  await clearAllUserData(userId);

  // 1. Stores: first create becomes default (see createStore)
  for (const s of DEMO_STORES) {
    await createStore(userId, {
      name: s.name,
      store_type: s.store_type,
      aisle_order: s.aisle_order,
      notes: s.notes ?? null,
    });
  }

  // 2. Recipes (create first so we can link meals)
  const recipeIdsByName = new Map<string, string>();
  for (const r of DEMO_RECIPES) {
    const recipe = await createRecipe(userId, {
      name: r.name,
      servings: r.servings,
      category: r.category ?? null,
      recipe_url: r.recipe_url ?? null,
      notes: r.notes ?? null,
    });
    await setRecipeIngredients(
      recipe.id,
      r.ingredients.map((i) => ({
        name: i.name,
        quantity_value: i.quantity_value,
        quantity_unit: i.quantity_unit,
        notes: i.notes ?? null,
      }))
    );
    if (r.is_favorite) {
      await toggleRecipeFavorite(recipe.id);
    }
    recipeIdsByName.set(r.name, recipe.id);
  }

  // 3. Meals (need IDs for list item linkage)
  const mealIdsByName = new Map<string, string>();
  const today = new Date();
  for (const m of DEMO_MEALS) {
    const mealDate = new Date(today);
    mealDate.setDate(today.getDate() + m.dateOffset);
    const recipeId = m.recipe_ref ? recipeIdsByName.get(m.recipe_ref) ?? null : null;
    const meal = await createMeal(userId, {
      name: m.name,
      meal_date: toDateString(mealDate),
      meal_slot: m.slot,
      custom_slot_name: m.custom_slot_name ?? null,
      recipe_id: recipeId,
      recipe_url: m.recipe_url ?? null,
      notes: m.notes ?? null,
    });
    await setMealIngredients(
      meal.id,
      m.ingredients.map((i) => ({
        name: i.name,
        quantity_value: i.quantity_value,
        quantity_unit: i.quantity_unit,
        notes: i.notes ?? null,
        brand_preference: i.brand_preference ?? null,
      }))
    );
    mealIdsByName.set(m.name, meal.id);
  }

  // 4. List items (resolve linked_meal_ids from meal names)
  const listItems: ListItemInsert[] = DEMO_LIST_ITEMS.map((item) => {
    const linkedIds = (item.linked_meal_refs ?? [])
      .map((name) => mealIdsByName.get(name))
      .filter((id): id is string => id != null);
    const { linked_meal_refs: _refs, ...rest } = item;
    return {
      ...rest,
      user_id: userId,
      normalized_name: normalize(item.name),
      linked_meal_ids: linkedIds,
    };
  });
  await insertListItems(userId, listItems);
}
